### ISSUE TITLE
Python Action运行错误

### ISSUE THREAD

**Issue by iuming** [monsterxcn/HEU-Checkin-COVID-19#3]
**Describe the bug**
手动运行Actions时，出现python错误，在checkin-python.log查到以下错误！

**To Reproduce**
1. Go to 'Actions'
2. Click on 'Run workflow'
3. Scroll down to 'Run workflow'

**Expected behavior**
部署后没有进行自动打卡，查看日志出现以下错误信息:
```
[error] :.:.:.:.: Except return :.:.:.:.:
[error] Python Error: 
 Traceback (most recent call last):
  File "Actions/checkin.py", line 78, in <module>
    csrfToken = csrfToken.pop().attrib["content"]
IndexError: pop from empty list
```

**Screenshots**
![image](https://user-images.githubusercontent.com/37214643/106089488-fe88ce80-6162-11eb-8627-cb4ed9b4c446.png)

**Comment by monsterxcn** [comment]
我也没搞清楚这是什么问题…今天打卡就是这个错误。
